import random
guesses = 7
num = random.randint (1,10)
answer = 0

def prRed(skk): print("\033[91m {}\033[00m" .format(skk)) 
def prGreen(skk): print("\033[92m {}\033[00m" .format(skk)) 
def prYellow(skk): print("\033[93m {}\033[00m" .format(skk)) 
def prLightPurple(skk): print("\033[94m {}\033[00m" .format(skk)) 
def prCyan(skk): print("\033[96m {}\033[00m" .format(skk)) 

prYellow("This is a number guessing game, which utilizes the implementation of the WHILE Loop and conditional statements, in which you will have to guess the right number from 1 to 10; the number is randomly auto-generated by the computer each time the game is played. You have only 7 guesses... Good luck!")

while num!= answer and guesses > 0:
  answer = int(input("Guess the number: "))
  guesses -= 1
  if answer < num:
    prCyan("Guess higher! Number of guesses left: " +str(guesses))
  elif answer > num:
    prLightPurple("Guess lower! Number of guesses left: " +str(guesses))
  else:
    prGreen("Correct number! The number was: " +str(num))

if answer != num:
  prRed("GAME OVER. You have run out of guesses. The number was: " +str(num))